name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Breaking'
    label: 'major'
  - title: 'Added'
    label: 'minor'
  - title: 'Fixed'
    label: 'patch'
exclude-labels:
  - 'skip-changelog'
  - 'release'
change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
  
