name: Pre-release
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get release tag
        id: get_release_tag
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Bump version
        run: |
          python bump_version.py ${{ steps.get_release_tag.outputs.tag_name }}-beta
      - name: Publish release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: true
          tag: ${{ steps.get_release_tag.outputs.tag_name }}-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
