name: Release Drafter

on:
  push:
    branches:
      - main
      - "*-hotfix"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          filter-by-commitish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
