name: Create release
on:
  release:
      types: # This configuration does not affect the page_build event above
        - created
jobs:  
  create-release-info:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: ""
          
